name: Docker Image BUILD AND PUSH

on:
  push:    
   branches:
   - master
   - release/*
   - pims  
  pull_request:
    branches: [ "master" , "pims" ]

jobs:

  buildAndpush:

    runs-on: ubuntu-latest

    steps:
    - id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: seapapa
        password: dckr_pat_y-koGhzYZ5v1WwqNBm3oDAYiJGk
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build --no-cache . --file scripts/docker/web-ui/Dockerfile --tag seapapa/web_ui_pims:${{ steps.commit.outputs.short }}
        docker tag seapapa/web_ui:${{ steps.commit.outputs.short }} seapapa/web_ui_pims:latest

    - name: Docker push
      run: | 
        docker push seapapa/web_ui_pims:${{ steps.commit.outputs.short }}
        docker push seapapa/web_ui_pims:latest
